### ISSUE TITLE
Add support for displayName

### ISSUE THREAD

**Issue by tsueho** [Ouest-France/goldap#27]
We have been using the terraform-provider-ldap TF module to programatically create AD groups (thank you)  and recently found the need to also update the displayName attribute of the AD group. ADSelf (the UI interface for LDAP) throws an error when saving a change as this field is deemed at required field in AdSelf.

Please can we have support for displayName too, I have actually created a branch with the change so can also push the relevant PR for review.

**Comment by pablo-ruth** [comment]
Hello @tsueho, I'm on vacation now but you can send the PR and I'll review it next week.

**Comment by tsueho** [comment]
Thanks @pablo-ruth  I have submitted PR's here:

https://github.com/Ouest-France/terraform-provider-ldap/pull/101
https://github.com/Ouest-France/goldap/pull/28

**Comment by pablo-ruth** [comment]
PR #28 merged

**Comment by pablo-ruth** [comment]
Ok thanks, the PR is merged.

Fixed by #30
